// torch_scorer.h
//
// Minimal TorchScript scorer for your retrieval pipeline (Scheme B).
//
// What this component does
// ------------------------
// - Load a TorchScript (.pt) model ONCE.
// - Given a batch of queries X (either float32* or uint8_t*), run model forward.
// - Output logits as a contiguous float array of shape [Q, D] where D MUST be <= 32.
// - The scorer is intended to be used ONLY at the beginning of the pipeline
//   (compute logits for all Q queries, then it is done).
//
// Input/Output conventions
// ------------------------
// - Input layout is row-major contiguous: X[q * in_dim + j].
// - in_dim is provided by the caller; typical values: 96, 128, 1536.
// - Output logits are row-major contiguous: logits[q * D + d].
// - D is inferred from the model output on the first call; enforced D <= 32.
//
// Threading
// ---------
// - torch_threads controls intra-op threads (e.g. GEMM/conv).
// - interop_threads controls inter-op threads.
// - (Optional) conversion from uint8 -> float can be parallelized.
//
// Notes
// -----
// - CPU-only (no CUDA). If your module was saved with CUDA ops, it will fail.
//
// Author: (generated by ChatGPT)

#pragma once

#include <cstdint>
#include <string>
#include <vector>

namespace torchpipe {

struct TorchScorerConfig {
  int torch_threads = 1;        // torch::set_num_threads
  int interop_threads = 1;      // torch::set_num_interop_threads
  bool try_set_interop = true;  // try to set interop threads once per process (safe: will warn if already set)

  // uint8 -> float conversion settings (only used for score_u8)
  float u8_scale = 1.0f;        // float_value = (u8 - u8_zero_point) * u8_scale
  float u8_zero_point = 0.0f;

  // Conversion parallelism (if OpenMP enabled, we use omp parallel for)
  int convert_threads = 1;

  // If true, we will call model.eval() and also disable autograd during scoring.
  bool eval_mode = true;
};

class TorchScorer {
public:
  TorchScorer(const std::string& model_path, const TorchScorerConfig& cfg);

  // Returns model output dimension (D). -1 if not known yet (before first forward).
  int output_dim() const { return out_dim_; }

  // Score float32 input: x shape [Q, in_dim] contiguous.
  // logits output: resized to [Q * D].
  void score_f32(const float* x, int64_t Q, int64_t in_dim, std::vector<float>& logits);

  // Score uint8 input: x shape [Q, in_dim] contiguous.
  // Internally converts to float32 (C++ conversion), then forward().
  void score_u8(const uint8_t* x, int64_t Q, int64_t in_dim, std::vector<float>& logits);

  // Optional warmup: run forward() n times (does not return logits).
  void warmup_f32(const float* x, int64_t Q, int64_t in_dim, int n);

private:
  void apply_thread_settings_once_();
  void enforce_output_shape_(int64_t Q, int64_t D) const;

private:
  TorchScorerConfig cfg_;
  std::string model_path_;

  // TorchScript module
  // (kept in .cpp to avoid heavy includes here; forward declared via void* is not ideal,
  // so we include torch headers only in .cpp and store module as a pImpl style pointer.)
  struct Impl;
  Impl* impl_ = nullptr;

  int out_dim_ = -1; // cached D from first forward
};

} // namespace torchpipe
